#!/bin/bash

HOME=`pwd`
for i in messyminus ccpwCVDZdk3 ccpwCVDZx2c ccpwCVTZdk3 ccpwCVTZx2c ccpwCVQZdk3 ccpwCVQZx2c SapDZdiff SapTZdiff SapQZdiff AHGBS9 AHGBS7 AHGBS5
do
cd $HOME/$i
bash run_all
done
